CREATE TABLE Covid19DailyReport (
  [Id] INT IDENTITY(1,1) NOT NULL, 
  [Fips] VARCHAR(255) DEFAULT NULL, 
  [Admin2] VARCHAR(255) DEFAULT NULL, 
  [ProvinceState] VARCHAR(255) DEFAULT NULL, 
  [CountryRegion] VARCHAR(255) DEFAULT NULL, 
  [LastUpdate] DATE DEFAULT NULL, 
  [Lat] DOUBLE PRECISION DEFAULT NULL, 
  [Long] DOUBLE PRECISION DEFAULT NULL, 
  [Confirmed] INT DEFAULT NULL, 
  [Deaths] INT DEFAULT NULL, 
  [Recovered] INT DEFAULT NULL, 
  [Active] INT DEFAULT NULL, 
  [CombinedKey] VARCHAR(255) DEFAULT NULL, 
  [IncidentRate] DOUBLE PRECISION DEFAULT NULL, 
  [CaseFatalityRatio] DOUBLE PRECISION DEFAULT NULL, 
  CONSTRAINT [PK_Covid19DailyReport] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE Covid19DailyReportUS (
  [Id] INT IDENTITY(1,1) NOT NULL, 
  [ProvinceState] VARCHAR(255) DEFAULT NULL, 
  [CountryRegion] VARCHAR(255) DEFAULT NULL, 
  [LastUpdate] DATE DEFAULT NULL, 
  [Lat] DOUBLE PRECISION DEFAULT NULL, 
  [LongField] DOUBLE PRECISION DEFAULT NULL, 
  [Confirmed] INT DEFAULT NULL, 
  [Deaths] INT DEFAULT NULL, 
  [Recovered] INT DEFAULT NULL, 
  [Active] INT DEFAULT NULL, 
  [Fips] INT DEFAULT NULL, 
  [IncidentRate] DOUBLE PRECISION DEFAULT NULL, 
  [TotalTestResult] INT DEFAULT NULL, 
  [PeopleHospitalized] INT DEFAULT NULL, 
  [CaseFatalityRatio] DOUBLE PRECISION DEFAULT NULL, 
  [Uid] INT DEFAULT NULL, 
  [Iso3] VARCHAR(255) DEFAULT NULL, 
  [TestingRate] DOUBLE PRECISION DEFAULT NULL, 
  [HospitalizationRate] DOUBLE PRECISION DEFAULT NULL, 
  CONSTRAINT [PK_Covid19DailyReportUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
